### ISSUE TITLE
关于bcm943224pciebt2

### ISSUE THREAD

**Issue by hdchieh** [laobamac/Hackintosh-I3-9100F-B365M-RX580#1]
我也使用了bcm943224pciebt2这张便宜的卡，除了不能continue camera，其他一切正常。
详见此[issue](https://github.com/zearp/Nucintosh/issues/79)

**Comment by hdchieh** [comment]
目前苦恼于 不能使用手机的麦克风与摄像头

**Comment by laobamac** [comment]
> 目前苦恼于 不能使用手机的麦克风与摄像头

你好！我目前也遇到了这个问题，应该和前段时间单向隔空的问题相同，原因在于手动注入的蓝牙驱动BrcmPatchRAM系列上，对于这个问题而言，等待开发者更新应该是最好的选择，感谢您的反馈与支持

**Comment by hdchieh** [comment]
> > 目前苦恼于 不能使用手机的麦克风与摄像头
> 
> 你好！我目前也遇到了这个问题，应该和前段时间单向隔空的问题相同，原因在于手动注入的蓝牙驱动BrcmPatchRAM系列上，对于这个问题而言，等待开发者更新应该是最好的选择，感谢您的反馈与支持

我在github上看到有人驱动成功了，但是我试了下依然不行。你可以尝试一下。[bcm943224pciebt2](https://github.com/evandavid/opencore-b460m-itx-i9-10900-rx6600/issues/5#issuecomment-1450101500)

**Comment by laobamac** [comment]
> > > 目前苦恼于 不能使用手机的麦克风与摄像头
> > 
> > 
> > 你好！我目前也遇到了这个问题，应该和前段时间单向隔空的问题相同，原因在于手动注入的蓝牙驱动BrcmPatchRAM系列上，对于这个问题而言，等待开发者更新应该是最好的选择，感谢您的反馈与支持
> 
> 我在github上看到有人驱动成功了，但是我试了下依然不行。你可以尝试一下。[bcm943224pciebt2](https://github.com/evandavid/opencore-b460m-itx-i9-10900-rx6600/issues/5#issuecomment-1450101500)

Well,I'll try it again,thanks for your support.
